apiVersion: v1
kind: Service
metadata:
  name: postgres-order
spec:
  selector:
    app: postgres-order
  ports:
    - protocol: TCP
      port: 5132  # Cluster port
      targetPort: 5432  # Container port
      nodePort: 30001 # Node port
  type: NodePort