services:
  postgres-order:
    image: postgres:latest
    container_name: postgres-order
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "service11"
      POSTGRES_PASSWORD: "service2025"
    volumes:
      - ../service-to-data/order-db-data:/var/lib/postgresql/data
      - ../service-to-env/init-order.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5132:5432"
    networks:
      - services-net

  postgres-report:
    image: postgres:latest
    container_name: postgres-report
    environment:
      POSTGRES_DB: "report_db"
      POSTGRES_USER: "service11"
      POSTGRES_PASSWORD: "service2025"
    volumes:
      - ../service-to-data/report-db-data:/var/lib/postgresql/data
      - ../service-to-env/init-report.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5332:5432"
    networks:
      - services-net

  order-service:
    image: order-service
    container_name: order
    env_file:
      - ../service-to-env/test.env
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - services-net
    depends_on:
      - postgres-order

  report-service:
    image: report-service
    container_name: report
    env_file:
      - ../service-to-env/report-test.env
    build:
      context: .
      dockerfile: report-service/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ../service-to-data/convert-test:/app/convert-test
    networks:
      - services-net
    depends_on:
      - postgres-report

  stock-service:
    image: stock-service
    container_name: stock
    env_file:
      - ../service-to-env/stock-test.env
    build:
      context: .
      dockerfile: stock-service/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - services-net


networks:
  services-net:
    name: services-net
    driver: bridge
    external: true