services:
  order-service:
    image: order-service
    build:
      context: .
      dockerfile: ./order-service/Dockerfile

    ports:
      - "8081:8081"
#    networks:
#      - microservices-net

  stock-service:
    image: stock-service
    build:
      context: .
      dockerfile: ./stock-service/Dockerfile
    ports:
      - "8082:8082"

#    networks:
#      - microservices-net

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#    networks:
#      - microservices-net
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#    networks:
#      - microservices-net

#networks:
#  microservices-net:
#    driver: bridge