server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        input-in-0:
          destination: order1-topic,order2-topic
          content-type: application/json
#        input-in-1:
#          destination: order2-topic
#          content-type: application/json


      kafka:
        binder:
          startOffset: earliest

          consumer-properties:
            allow:
              auto:
                create:
                  topics: false

          brokers: localhost:9092