server:
  port: ${STOCK_PORT}

spring:
  webclient:
    url:
      report: ${REPORT_URL}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    stream:
      bindings:
        input-in-0:
          destination: order1-topic,order2-topic
          content-type: application/json

      kafka:
        binder:
          startOffset: earliest
#          startOffset: latest

          consumer-properties:
            allow:
              auto:
                create:
                  topics: false

#          brokers: localhost:9092
          brokers: ${STOCK_BROKERS_URL}