apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: localhost:5000/order-service:latest  # image name
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-service-env  # ConfigMap environment variables