server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    order:
      postgres:
        url: ${ORDER_DATABASE_URL}
        username: ${ORDER_DATABASE_USER}
        password: ${ORDER_DATABASE_PASSWORD}
  cloud:
    stream:
      bindings:
        output1:
          destination: "order1-topic"
          content-type: application/json
        output2:
          destination: "order2-topic"
          content-type: application/json
      kafka:
        binder:
          brokers: ${ORDER_BROKERS_URL}

# for logstash_____
#logging:
#  level:
#    root: INFO

#  file:
#    name: logs/app.log


management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"  # open endpoints
  endpoint:
    health:
      show-details: always
  server:
    port: 8081
  prometheus:
  metrics:
    export:
      enable: true