apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/kuber/data/report-service/convert-test/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""