apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kuber/data/report-service/convert-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi