apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8083  # Port in cluster
      targetPort: 8083  # Container port
  type: ClusterIP
