apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: report-pv
  storageClassName: ""