apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: stock-pv
  storageClassName: ""