apiVersion: v1
kind: PersistentVolume
metadata:
  name: stock-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/michaeleremin/data-test-stock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""