apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 8082  # Port in cluster
      targetPort: 8082  # Container port
  type: ClusterIP
