services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - services-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - services-net
    depends_on:
      - zookeeper

networks:
  services-net:
    name: services-net
    driver: bridge
    external: true
